version: "3.8"
services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    command: npm run dev
    env_file:
      - ./.env
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      - mongo
      - parser

  parser:
    build: ./parser
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
